language: julia
arch:
  - amd64
os:
  - linux
  - osx
  # - windows
notifications:
  email: false
branches:
  only:
  - master
codecov: true
julia:
  # - nightly
  - 1.0
  - 1.4
jobs:
  allow_failures:
    - julia: 1.4
  include:
  - stage: "Documentation"
    julia: 1.0
    os: linux
    script:
      # - julia --color=yes -e 'using Pkg; Pkg.add("Documenter")'
      - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - julia --color=yes --project=docs/ docs/make.jl
    after_success: skip
# after_success:
#   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
#   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
